---
- name: Set facts
  hosts: all
  gather_facts: false
  roles:
    - role: facts

- ansible.builtin.import_playbook: stop_cluster.yml

- name: Halt servers to gracefully poweroff
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Reboot
      ansible.builtin.shell: |
        reboot

    - name: Wait to got up
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started
