---
- name: Set facts
  hosts: all
  gather_facts: false
  roles:
    - role: facts

- name: Undo cluster setup
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Run K3s Uninstall script [server]
      when: "'server' in group_names"
      ansible.builtin.command:
        cmd: k3s-uninstall.sh
        removes: "{{ path_prefix }}/var/lib/rancher/k3s/*"
    - name: Run K3s Uninstall script [agent]
      when: "'agent' in group_names or 'agent_droid' in group_names"
      ansible.builtin.command:
        cmd: k3s-agent-uninstall.sh
        removes: "{{ path_prefix }}/var/lib/rancher/k3s/*"
    - name: Remove user kubeconfig
      ansible.builtin.file:
        path: ~{{ ansible_user }}/.kube/config
        state: absent
    - name: Remove k3s install script
      ansible.builtin.file:
        path: "{{ bin_dir }}/k3s-install.sh"
        state: absent
    - name: Remove contents of K3s server location
      when: k3s_location is defined
      ansible.builtin.shell:
        cmd: "rm -rf {{ k3s_location }}/*"
        removes: "{{ k3s_location }}/*"
    - name: Remove K3s config
      when: server_config_yaml is defined
      ansible.builtin.file:
        path: "{{ path_prefix }}/etc/rancher/k3s/config.yaml"
        state: absent
