---
- name: Set facts
  hosts: all
  gather_facts: false
  roles:
    - role: facts

- ansible.builtin.import_playbook: stop_cluster.yml

- name: Reboot servers
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Shutdown node
      ansible.builtin.shell: |
        /sbin/shutdown --halt now

    - name: Wait to go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started
