---
- name: Set facts
  hosts: all
  gather_facts: false
  roles:
    - role: facts

- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  tasks:
    - name: Include prereq role
      include_role:
        name: prereq
      when: "not is_android"
    - name: Include airgap role
      include_role:
        name: airgap
      when: "not is_android"
    - name: Include raspberrypi role
      include_role:
        name: raspberrypi
      when: "not is_android"

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts:
    - agent
    - agent_droid
  become: true
  roles:
    - role: k3s_agent
