---
- name: Set facts
  hosts: all
  gather_facts: false
  roles:
    - role: facts

# Servers should be restarted sequientally to avoid etcd learner issues
# Agents have no such limitation
- name: Upgrade K3s Servers
  hosts: server
  become: true
  serial: 1
  roles:
    - role: k3s_upgrade

- name: Upgrade K3s Agents
  hosts:
    - agent
    - agent_droid
  become: true
  roles:
    - role: k3s_upgrade
