---
# with_fileglob doesn't work with remote_src, it tries to find the file on the
# local control-plane instead of the remote host. Shell supports wildcards.
- name: Save current K3s service
  ansible.builtin.shell:
    cmd: "cp {{ systemd_dir }}/k3s*.service /tmp/"
  changed_when: true

- name: Install new K3s Version
  ansible.builtin.command:
    cmd: "{{ bin_dir }}/k3s-install.sh"
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_BIN_DIR: "{{ bin_dir }}"
    INSTALL_K3S_SKIP_ENABLE: "{{ 'false' if is_android else 'true' }}"
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_EXEC: "{{ 'server' if 'server' in group_names else 'agent' }}"
  changed_when: true

- name: Restore K3s service
  ansible.builtin.shell:
    cmd: "mv /tmp/k3s*.service {{ systemd_dir }}/"
  changed_when: true
  when: "not is_android"

- name: Restart K3s service [server]
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: k3s
  when: "'server' in group_names and not is_android"

- name: Restart K3s service [agent]
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: k3s-agent
  when: "'agent' in group_names and not is_android"

- name: Enable and check K3s termux-service
  ansible.builtin.command:
    cmd: sv down k3s-agent && sv up k3s-agent
  when: "'agent' in group_names and is_android"
